"""Changed Record is_household field

Revision ID: 19c36e64a7eb
Revises: a93996f2b365
Create Date: 2022-04-04 23:33:33.411807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c36e64a7eb'
down_revision = 'a93996f2b365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
