"""Changed Record is_household field

Revision ID: 3affc8751454
Revises: 19c36e64a7eb
Create Date: 2022-04-04 23:48:09.023138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3affc8751454'
down_revision = '19c36e64a7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('record_ibfk_1', 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key('record_ibfk_1', 'record', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###
