"""added uniqueconstraint to records

Revision ID: 363357119bbb
Revises: a91425042b44
Create Date: 2022-04-12 03:05:17.706012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363357119bbb'
down_revision = 'a91425042b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_record', 'record', ['name', 'address_id', 'company'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_record', 'record', type_='unique')
    # ### end Alembic commands ###
